# Names of 25 common products
PRODUCT_NAME_STRINGS = [
    "medicine",
    "pain killers",
    "condoms",
    "antihistamines",
    "antibiotics",
    "pork meat",
    "chicken",
    "ham",
    "fish",
    "beef",
    "rice",
    "beans",
    "potato",
    "carrot",
    "pumpkin",
    "apple",
    "tomato",
    "guava",
    "pineapple",
    "grapes",
    "hydrogen",
    "helium",
    "oxygen",
    "sodium",
    "carbon",
    "wood",
    "cement",
    "marble",
    "bricks",
    "nails",
    ] + ["product {}".format(i) for i in range(26, 101)]